### PR TITLE
i2: support multiple categorical covariates

### LINKED ISSUE #2: Multiple covariates not working
To replicate this bug pass any covariate formula with more than 1 covariate.

```{r}
mod <- epikinetics::scova$new(file_path = system.file("delta_full.rds", package = "epikinetics"), 
                              covariate_formula = ~0 + infection_history + last_vax_type) 
```

An error occurs in the `build_covariate_lookup_table` function: this builds a covariate lookup table to recover covariate names after fitting. 

But I think the R code processing the fits will also only work if there is a single covariate (see e.g. `summarise_pop_fit`)

### PR DESCRIPTION
**Pull request by hillalex**
Closes #2 

This PR:
* rewrites the logic to build the covariate lookup table to support multiple regression covariates
* adds test cases of the above logic
* amends fit processing logic to support the case where there are no regression variables

I've also added a couple of files to the `testthat` directory which can be used to manually run the model with no and multiple covariates and plot the results, to sanity check the results. I got the following plots using the Delta wave data, but @thimotei will be better placed to judge whether these look reasonable or not:

With regression model ~0 + infection_history:last_vax_type

multipleplot1
multipleplot2
multiple3

With no regression model:

nocovariates1
plot2
nocovariates3

The graphs of the individual trajectories look a bit different betwen the no and the multiple covariate models. I would expect them to be almost identical, but I assume this is just because I didn't run the models for very long (see `manual-test-x.R` files, both were run with 

```
mod$fit(chains = 4,
        parallel_chains = 4,
        iter_warmup = 50,
        iter_sampling = 200,
        threads_per_chain = 4)
 ```
 
 Otherwise these do look reasonable to my untrained eye...

### CODE REVIEW

File: R/scova.R [hunk 1]
```diff
@@ -63,41 +63,13 @@ scova <- R6::R6Class(
       # Identify columns with no variance and remove them
       variance_per_column <- apply(mm, 2, var)
       relevant_columns <- which(variance_per_column != 0)
-      mm_reduced <- mm[, relevant_columns]
+      mm_reduced <- mm[, relevant_columns, drop = FALSE]
```
Comment (hillalex) [inline R/scova.R]: just in case this becomes a 1 column matrix, stop it from being converted to a vector with colnames removed

File: tests/testthat/plot.R [hunk 2]
```diff
@@ -0,0 +1,71 @@
+library(ggplot2)
```
Comment (hillalex) [inline tests/testthat/plot.R]: added this file just for manual testing

**Comment by hillalex** [comment]
Re the issue I mentioned with the resampling hitting R's maximum vector limit: I think it was just a coincidence that I saw this for the first time when running without a regression model. I must have just taken more draws or something when I saw the error. 

I'll raise a separate issue for testing the resampling more thoroughly, and re-writing in a way that uses less memory if neccessary (e.g. splitting up the vector and doing the resampling one group at a time). Based on our chat earlier it seems like we might want to look into the resampling anyway, as it might not be working exactly as intended.

File: R/scova.R [hunk 3]
```diff
@@ -63,41 +63,13 @@ scova <- R6::R6Class(
...
-      # https://github.com/Rdatatable/data.table/issues/850#issuecomment-259466153
-      p <- NULL
-
-      # .I is a special symbol in data.table for row number
-      dt[, p := .I]
-
-      # Reorder columns to have 'i' first
-      data.table::setcolorder(dt, "p")
-      private$covariate_lookup_table <- dt
+      private$covariate_lookup_table <- build_covariate_lookup_table(private$data,
```
Comment (hillalex) [inline R/scova.R]: moved logic out to own function, mostly for ease of unit testing (but also could be re-used if/when we add CT model)

File: R/scova.R [hunk 4]
```diff
@@ -228,7 +216,8 @@ scova <- R6::R6Class(
     #' for required columns: \code{vignette("data", package = "epikinetics")}.
     #' @param file_path Optional file path to model inputs in CSV format. One of data or file must be provided.
     #' @param priors Object of type \link[epikinetics]{scova_priors}. Default scova_priors().
-    #' @param covariate_formula Formula specifying hierarchical structure of model. Default ~0.
+    #' @param covariate_formula Formula specifying linear regression model. Note all variables in the formula
+    #' will be treated as categorical variables. Default ~0.
```
Comment (thimotei) [inline R/scova.R]: So, I might be missing something, but in principle there is no need to treat covariates as categorical. There is certainly a need for continuous variables for the Ct version of the model and I can imagine others wanting continuous variables for this model possibly. It shouldn't change the overall regression parameters. It might make the covariate name recovery a bit more strange, and perhaps the "bespoke" code I wrote for this model might need some tweaking. But we should aim to include continuous variables at some point too.

**Review by thimotei — APPROVED** [review]
Looks good overall! You would expect the results to be slightly different between the models with and without covariates, as they have different statistical model structures. But they look different in exactly the way you'd expect, so I think its working perfectly.

File: R/scova.R (hunk 4 above)
Comment (hillalex) [reply R/scova.R]: Yeah, totally agree that we should accept these in principle, will just be a bit fiddly to get that working so figured this was a reasonable intermediate step. Will add an issue :+1:
